"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export const translations = {
  en: {
    // Navigation
    home: "Home",
    about: "About",
    projects: "Projects",
    blog: "Blog",
    contact: "Contact",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    // Home page
    webDeveloper: "Web & Software Developer",
    heroTitle: "Interactive apps with polished engineering.",
    heroDescription: "I build interfaces that move naturally, APIs that scale reliably, and software that supports real business value. Explore work across frontend, backend, and full-stack delivery.",
    seeProjects: "See Projects",
    learnAbout: "Learn About Me",
    projectsDelivered: "Projects delivered",
    yearsExperience: "Years experience",
    techStack: "Tech stack",
    designSystems: "Design systems built for scale",
    designSystemsDesc: "Reusable UI patterns, accessibility-first layouts, and component-driven workflows for fast delivery.",
    fullStack: "Full-stack product delivery",
    fullStackDesc: "From frontend interfaces to backend APIs, I ship end-to-end solutions with reliability and speed.",
    highPerformance: "High-performance experiences",
    highPerformanceDesc: "I optimize loading, interactions, and visuals so products feel polished and responsive.",
    // About page
    aboutMe: "About Me",
    aboutTitle: "Solving problems with precise engineering.",
    aboutDesc: "I combine frontend craftsmanship with backend reliability to build products that users enjoy and teams can maintain. My work is grounded in clean architecture, fast interfaces, and a clear development process.",
    yearsCoding: "Years coding",
    deliveredProjects: "Delivered projects",
    careerHighlights: "Career highlights",
    fullStackLaunches: "Full-stack launches",
    fullStackDetail: "Delivered multiple production apps with React, Next.js, and Node.js integrations.",
    uxPerformance: "UX and performance focus",
    uxDetail: "Built polished user interfaces with accessibility, speed, and animation in mind.",
    softwareEngineering: "Software engineering foundation",
    softwareDetail: "Built backend services, REST APIs, and scalable tooling for modern web products.",
    howIWork: "How I work",
    plan: "Plan",
    planDesc: "Understand the problem, define goals, and align the product with user and business needs.",
    build: "Build",
    buildDesc: "Write reliable code with modern tools, reusable patterns, and polished UI interactions.",
    refine: "Refine",
    refineDesc: "Test, optimize, and maintain the product so it stays fast and easy to expand.",
    // Projects page
    projectsLabel: "Projects",
    projectsTitle: "Real work with real product focus.",
    projectsDesc: "These projects highlight responsive interfaces, solid architecture, and practical developer tooling.",
    portfolioDashboard: "Portfolio Dashboard",
    portfolioRole: "UI + interaction design",
    portfolioSummary: "A clean responsive developer dashboard with animated UI components and fast load behavior.",
    taskMgmt: "Task Management App",
    taskRole: "Full-stack delivery",
    taskSummary: "A productivity tool built for teams, with task states, persistence, and an intuitive workflow.",
    apiSync: "API Sync Service",
    apiRole: "Backend architecture",
    apiSummary: "A service that connects multiple APIs, normalizes data, and keeps systems in sync.",
    designSystem: "Design System Kit",
    designRole: "Component library",
    designSummary: "A reusable style system created to accelerate design consistency across apps.",
    // Blog page
    articles: "Articles",
    blogTitle: "Thoughts on web development, software architecture, and modern tooling.",
    blogDesc: "Sharing insights from years of building scalable web applications and tackling real-world engineering challenges.",
    readMore: "Read →",
    minRead: "min read",
    // Contact page
    contactLabel: "Contact",
    contactTitle: "Creating meaningful impact, together.",
    contactDesc: "I'm open to web development, software engineering, and product collaborations. Reach out to discuss an idea, contractor opportunity, or technical project.",
    email: "Email",
    visitProfile: "Visit profile",
    // Settings page
    settingsTitle: "Customize your experience",
    settingsDescription: "Personalize your portfolio viewing preferences.",
    languageTitle: "Language",
    languageDescription: "Choose your preferred language for the website.",
    accessibilityTitle: "Accessibility",
    fontSizeLabel: "Font Size",
    notificationsTitle: "Notifications",
    notificationsDescription: "Get notified about important updates and messages.",
    savedNote: "Your selected language and display preferences are saved locally.",
    // Services
    servicesTitle: "Engineering Solutions",
    servicesSubtitle: "Practical expertise across design, development, and digital services.",
    webDev: "Web Development",
    webDevDesc: "Building responsive, high-performance websites with modern technologies like React, Next.js, and Node.js.",
    graphicDesign: "Graphic Design",
    graphicDesignDesc: "Creating visual identities, UI/UX designs, and marketing materials that communicate your brand effectively.",
    eServices: "E-Services",
    eServicesDesc: "Digital solutions including online platforms, e-commerce, and automated workflows for modern businesses.",
    dataAnalysis: "Data Analysis",
    dataAnalysisDesc: "Transforming raw data into actionable insights through visualization, reporting, and statistical analysis.",
    // FAQ
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: "Common questions about my services, availability, and working process.",
    faqServicesQuestion: "What services do you offer?",
    faqServicesAnswer: "I offer web development (React, Next.js, Node.js), graphic design, e-services (e-commerce, online platforms), and data analysis. My focus is on engineering solutions that deliver real business value.",
    faqFreelanceQuestion: "Are you available for freelance?",
    faqFreelanceAnswer: "Yes, I am available for freelance projects, contract work, and consulting. I work with startups, agencies, and businesses of all sizes. Feel free to reach out to discuss your project needs.",
    faqTimelineQuestion: "What is your typical project timeline?",
    faqTimelineAnswer: "Timelines vary based on project scope. A simple landing page takes 1-2 weeks, while full-stack applications typically take 4-8 weeks. I provide detailed timelines during our initial consultation and keep you updated throughout the process.",
    // Process
    processTitle: "My Process",
    processSubtitle: "A structured approach to delivering high-quality solutions",
    processPlanning: "Planning",
    processPlanningDesc: "Understanding requirements, defining project scope, and creating a roadmap aligned with business goals.",
    processDevelopment: "Development",
    processDevelopmentDesc: "Building scalable solutions with clean code, modern technologies, and best practices.",
    processTesting: "Testing",
    processTestingDesc: "Rigorous quality assurance, performance optimization, and cross-browser compatibility checks.",
    processDeployment: "Deployment",
    processDeploymentDesc: "Smooth launch with CI/CD pipelines, monitoring setup, and post-launch support.",
    // Education
    educationTitle: "Education & Certifications",
    educationSubtitle: "Continuous learning and professional development",
    educationA2: "A2 Certificate - German Language",
    educationA2Institution: "Goethe-Institut",
    educationA2Desc: "Official certification proving proficiency in German language at the elementary level, enabling professional communication in German-speaking environments.",
    educationData: "Data & DevOps Engineering",
    educationDataInstitution: "ALX Africa / Holberton School",
    educationDataDesc: "Comprehensive training in data engineering, cloud infrastructure, CI/CD pipelines, and DevOps best practices with hands-on project experience.",
    educationFullStack: "Full Stack Software Engineering",
    educationFullStackInstitution: "ALX Africa / Holberton School",
    educationFullStackDesc: "Intensive program covering frontend and backend development, system engineering, and low-level programming with C and Python.",
    certification: "Certification",
    degree: "Degree",
    viewCredential: "View Credential",
    // Hero
    heroProjects: "Projects",
    heroClients: "Clients",
    downloadCV: "Download CV",
    byTheNumbers: "By the Numbers",
  },
  es: {
    // Navigation
    home: "Inicio",
    about: "Acerca de",
    projects: "Proyectos",
    blog: "Blog",
    contact: "Contacto",
    settings: "Configuración",
    language: "Idioma",
    theme: "Tema",
    // Home page
    webDeveloper: "Desarrollador Web y Software",
    heroTitle: "Aplicaciones interactivas con ingeniería pulida.",
    heroDescription: "Construyo interfaces que se mueven naturalmente, APIs que escalan de manera confiable y software que respalda valor empresarial real. Explora el trabajo en desarrollo frontend, backend y full-stack.",
    seeProjects: "Ver Proyectos",
    learnAbout: "Aprende sobre mí",
    projectsDelivered: "Proyectos entregados",
    yearsExperience: "Años de experiencia",
    techStack: "Stack de tecnología",
    designSystems: "Sistemas de diseño construidos para escala",
    designSystemsDesc: "Patrones UI reutilizables, diseños accesibles en primer lugar y flujos impulsados por componentes para entrega rápida.",
    fullStack: "Entrega de producto full-stack",
    fullStackDesc: "Desde interfaces frontend hasta APIs backend, entrego soluciones de extremo a extremo con confiabilidad y velocidad.",
    highPerformance: "Experiencias de alto rendimiento",
    highPerformanceDesc: "Optimizo la carga, interacciones y visuals para que los productos se sientan pulidos y responsivos.",
    // About page
    aboutMe: "Acerca de mí",
    aboutTitle: "Resuelve problemas con código e ingeniería sólida.",
    aboutDesc: "Combino la artesanía frontend con la confiabilidad backend para construir productos que los usuarios disfruten y que los equipos puedan mantener. Mi trabajo se basa en arquitectura limpia, interfaces rápidas y un proceso de desarrollo claro.",
    yearsCoding: "Años programando",
    deliveredProjects: "Proyectos entregados",
    careerHighlights: "Logros destacados",
    fullStackLaunches: "Lanzamientos full-stack",
    fullStackDetail: "Entregué múltiples aplicaciones de producción con integraciones de React, Next.js y Node.js.",
    uxPerformance: "Enfoque en UX y rendimiento",
    uxDetail: "Construí interfaces de usuario pulidas con accesibilidad, velocidad y animación en mente.",
    softwareEngineering: "Base de ingeniería de software",
    softwareDetail: "Construí servicios backend, API REST y herramientas escalables para productos web modernos.",
    howIWork: "Cómo trabajo",
    plan: "Planificar",
    planDesc: "Comprenda el problema, defina objetivos y alinee el producto con las necesidades de usuarios y negocios.",
    build: "Construir",
    buildDesc: "Escribe código confiable con herramientas modernas, patrones reutilizables e interacciones UI pulidas.",
    refine: "Refinar",
    refineDesc: "Prueba, optimiza y mantén el producto para que sea rápido y fácil de expandir.",
    // Projects page
    projectsLabel: "Proyectos",
    projectsTitle: "Trabajo real con enfoque de producto real.",
    projectsDesc: "Estos proyectos destacan interfaces receptivas, arquitectura sólida y herramientas de desarrollo prácticas.",
    portfolioDashboard: "Panel de Portafolio",
    portfolioRole: "Diseño UI + interacción",
    portfolioSummary: "Un panel de desarrollo limpio y receptivo con componentes UI animados y comportamiento de carga rápida.",
    taskMgmt: "Aplicación de Gestión de Tareas",
    taskRole: "Entrega full-stack",
    taskSummary: "Una herramienta de productividad construida para equipos, con estados de tareas, persistencia y flujo de trabajo intuitivo.",
    apiSync: "Servicio de Sincronización de API",
    apiRole: "Arquitectura backend",
    apiSummary: "Un servicio que conecta múltiples API, normaliza datos y mantiene los sistemas sincronizados.",
    designSystem: "Kit de Sistema de Diseño",
    designRole: "Biblioteca de componentes",
    designSummary: "Un sistema de estilo reutilizable creado para acelerar la consistencia de diseño en aplicaciones.",
    // Blog page
    articles: "Artículos",
    blogTitle: "Pensamientos sobre desarrollo web, arquitectura de software y herramientas modernas.",
    blogDesc: "Compartiendo insights de años construcción de aplicaciones web escalables y abordando desafíos de ingeniería del mundo real.",
    readMore: "Leer →",
    minRead: "min de lectura",
    // Contact page
    contactLabel: "Contacto",
    contactTitle: "Construyamos algo significativo juntos.",
    contactDesc: "Estoy abierto a desarrollo web, ingeniería de software y colaboraciones de producto. Comunícate para discutir una idea, oportunidad de contratista o proyecto técnico.",
    email: "Correo electrónico",
    visitProfile: "Visitar perfil",
    // Settings page
    settingsTitle: "Personaliza tu experiencia",
    settingsDescription: "Ajusta las preferencias de visualización de tu portafolio.",
    languageTitle: "Idioma",
    languageDescription: "Elige tu idioma preferido para el sitio web.",
    accessibilityTitle: "Accesibilidad",
    fontSizeLabel: "Tamaño de fuente",
    notificationsTitle: "Notificaciones",
    notificationsDescription: "Recibe actualizaciones importantes y mensajes.",
    savedNote: "Tus ajustes se guardan localmente.",
    // Services
    servicesTitle: "Soluciones de Ingeniería",
    servicesSubtitle: "Experiencia práctica en diseño, desarrollo y servicios digitales.",
    webDev: "Desarrollo Web",
    webDevDesc: "Creando sitios web responsivos y de alto rendimiento con tecnologías modernas como React, Next.js y Node.js.",
    graphicDesign: "Diseño Gráfico",
    graphicDesignDesc: "Creando identidades visuales, diseños UI/UX y materiales de marketing que comunican tu marca efectivamente.",
    eServices: "Servicios Electrónicos",
    eServicesDesc: "Soluciones digitales incluyendo plataformas en línea, comercio electrónico y flujos de trabajo automatizados.",
    dataAnalysis: "Análisis de Datos",
    dataAnalysisDesc: "Transformando datos en información procesable a través de visualización, reportes y análisis estadístico.",
    // FAQ
    faqTitle: "Preguntas Frecuentes",
    faqSubtitle: "Preguntas comunes sobre mis servicios, disponibilidad y proceso de trabajo.",
    faqServicesQuestion: "¿Qué servicios ofreces?",
    faqServicesAnswer: "Ofrezco desarrollo web (React, Next.js, Node.js), diseño gráfico, servicios electrónicos (e-commerce, plataformas en línea) y análisis de datos. Mi enfoque está en soluciones de ingeniería que generan valor real para los negocios.",
    faqFreelanceQuestion: "¿Estás disponible para freelance?",
    faqFreelanceAnswer: "Sí, estoy disponible para proyectos freelance, trabajo por contrato y consultoría. Trabajo con startups, agencias y empresas de todos los tamaños. No dudes en contactarme para discutir las necesidades de tu proyecto.",
    faqTimelineQuestion: "¿Cuál es tu cronograma típico de proyecto?",
    faqTimelineAnswer: "Los cronogramas varían según el alcance del proyecto. Una página de destino simple toma 1-2 semanas, mientras que aplicaciones full-stack típicamente toman 4-8 semanas. Proporciono cronogramas detallados durante nuestra consulta inicial y te mantengo actualizado durante todo el proceso.",
    // Process
    processTitle: "Mi Proceso",
    processSubtitle: "Un enfoque estructurado para entregar soluciones de alta calidad",
    processPlanning: "Planificación",
    processPlanningDesc: "Comprensión de requisitos, definición del alcance del proyecto y creación de una hoja de ruta alineada con los objetivos comerciales.",
    processDevelopment: "Desarrollo",
    processDevelopmentDesc: "Construcción de soluciones escalables con código limpio, tecnologías modernas y mejores prácticas.",
    processTesting: "Pruebas",
    processTestingDesc: "Aseguramiento de calidad riguroso, optimización de rendimiento y verificaciones de compatibilidad entre navegadores.",
    processDeployment: "Despliegue",
    processDeploymentDesc: "Lanzamiento fluido con pipelines CI/CD, configuración de monitoreo y soporte post-lanzamiento.",
    // Education
    educationTitle: "Educación y Certificaciones",
    educationSubtitle: "Aprendizaje continuo y desarrollo profesional",
    educationA2: "Certificado A2 - Idioma Alemán",
    educationA2Institution: "Goethe-Institut",
    educationA2Desc: "Certificación oficial que acredita competencia en idioma alemán a nivel elemental, permitiendo comunicación profesional en entornos de habla alemana.",
    educationData: "Ingeniería de Datos y DevOps",
    educationDataInstitution: "ALX Africa / Holberton School",
    educationDataDesc: "Formación integral en ingeniería de datos, infraestructura en la nube, pipelines CI/CD y mejores prácticas DevOps con experiencia práctica en proyectos.",
    educationFullStack: "Ingeniería de Software Full Stack",
    educationFullStackInstitution: "ALX Africa / Holberton School",
    educationFullStackDesc: "Programa intensivo que cubre desarrollo frontend y backend, ingeniería de sistemas y programación de bajo nivel con C y Python.",
    certification: "Certificación",
    degree: "Título",
    viewCredential: "Ver Credencial",
    // Hero
    heroProjects: "Proyectos",
    heroClients: "Clientes",
    downloadCV: "Descargar CV",
    byTheNumbers: "En Números",
  },
  fr: {
    // Navigation
    home: "Accueil",
    about: "À propos",
    projects: "Projets",
    blog: "Blog",
    contact: "Contact",
    settings: "Paramètres",
    language: "Langue",
    theme: "Thème",
    // Home page
    webDeveloper: "Développeur Web et Logiciel",
    heroTitle: "Des applications interactives avec une ingénierie soignée.",
    heroDescription: "Je crée des interfaces qui se déplacent naturellement, des API qui évoluent de manière fiable et des logiciels qui créent une véritable valeur commerciale. Explorez le travail en développement frontend, backend et full-stack.",
    seeProjects: "Voir les Projets",
    learnAbout: "En savoir plus sur moi",
    projectsDelivered: "Projets livrés",
    yearsExperience: "Années d'expérience",
    techStack: "Stack technologique",
    designSystems: "Systèmes de conception construits à l'échelle",
    designSystemsDesc: "Motifs UI réutilisables, mises en page axées sur l'accessibilité et flux pilotés par composants pour une livraison rapide.",
    fullStack: "Livraison de produits full-stack",
    fullStackDesc: "Des interfaces frontend aux API backend, je livre des solutions de bout en bout avec fiabilité et rapidité.",
    highPerformance: "Expériences haute performance",
    highPerformanceDesc: "J'optimise le chargement, les interactions et les visuels pour que les produits se sentent polis et réactifs.",
    // About page
    aboutMe: "À propos de moi",
    aboutTitle: "Résoudre les problèmes avec du code et une ingénierie solide.",
    aboutDesc: "Je combine l'artisanat frontend avec la fiabilité backend pour construire des produits que les utilisateurs apprécient et que les équipes peuvent maintenir. Mon travail est fondé sur une architecture propre, des interfaces rapides et un processus de développement clair.",
    yearsCoding: "Années de codage",
    deliveredProjects: "Projets livrés",
    careerHighlights: "Jalons de carrière",
    fullStackLaunches: "Lancements full-stack",
    fullStackDetail: "J'ai livré plusieurs applications de production avec les intégrations React, Next.js et Node.js.",
    uxPerformance: "Focus UX et performance",
    uxDetail: "J'ai construit des interfaces utilisateur soignées avec l'accessibilité, la vitesse et l'animation à l'esprit.",
    softwareEngineering: "Fondation d'ingénierie logicielle",
    softwareDetail: "J'ai construit des services backend, des API REST et des outils évolutifs pour les produits web modernes.",
    howIWork: "Comment je travaille",
    plan: "Planifier",
    planDesc: "Comprendre le problème, définir les objectifs et aligner le produit avec les besoins des utilisateurs et de l'entreprise.",
    build: "Construire",
    buildDesc: "Écrivez du code fiable avec des outils modernes, des modèles réutilisables et des interactions UI soignées.",
    refine: "Affiner",
    refineDesc: "Testez, optimisez et maintenez le produit pour qu'il reste rapide et facile à développer.",
    // Projects page
    projectsLabel: "Projets",
    projectsTitle: "Un vrai travail avec un vrai focus produit.",
    projectsDesc: "Ces projets mettent en évidence des interfaces réactives, une architecture solide et des outils de développement pratiques.",
    portfolioDashboard: "Tableau de Bord Portfolio",
    portfolioRole: "Conception UI + interaction",
    portfolioSummary: "Un tableau de bord pour développeur propre et réactif avec des composants UI animés et un comportement de chargement rapide.",
    taskMgmt: "Application de Gestion des Tâches",
    taskRole: "Livraison full-stack",
    taskSummary: "Un outil de productivité construit pour les équipes, avec états de tâches, persistance et flux de travail intuitif.",
    apiSync: "Service de Synchronisation API",
    apiRole: "Architecture backend",
    apiSummary: "Un service qui connecte plusieurs API, normalise les données et maintient les systèmes synchronisés.",
    designSystem: "Kit de Système de Design",
    designRole: "Bibliothèque de composants",
    designSummary: "Un système de style réutilisable créé pour accélérer la cohérence du design sur les applications.",
    // Blog page
    articles: "Articles",
    blogTitle: "Pensées sur le développement web, l'architecture logicielle et les outils modernes.",
    blogDesc: "Partage d'idées après des années de création d'applications web scalables et de résolution de défis d'ingénierie du monde réel.",
    readMore: "Lire →",
    minRead: "min de lecture",
    // Contact page
    contactLabel: "Contact",
    contactTitle: "Construisons quelque chose de significatif ensemble.",
    contactDesc: "Je suis ouvert au développement web, à l'ingénierie logicielle et aux collaborations de produits. Contactez-moi pour discuter d'une idée, d'une opportunité de contrat ou d'un projet technique.",
    email: "E-mail",
    visitProfile: "Visiter le profil",
    // Settings page
    settingsTitle: "Personnalisez votre expérience",
    settingsDescription: "Personnalisez les préférences d'affichage de votre portfolio.",
    languageTitle: "Langue",
    languageDescription: "Choisissez votre langue préférée pour le site.",
    accessibilityTitle: "Accessibilité",
    fontSizeLabel: "Taille de police",
    notificationsTitle: "Notifications",
    notificationsDescription: "Recevez des mises à jour et des messages importants.",
    savedNote: "Vos préférences sont enregistrées localement.",
    // Services
    servicesTitle: "Solutions d'Ingénierie",
    servicesSubtitle: "Expertise pratique en design, développement et services numériques.",
    webDev: "Développement Web",
    webDevDesc: "Création de sites web responsifs et performants avec des technologies modernes comme React, Next.js et Node.js.",
    graphicDesign: "Design Graphique",
    graphicDesignDesc: "Création d'identités visuelles, designs UI/UX et matériels marketing qui communiquent efficacement votre marque.",
    eServices: "Services Électroniques",
    eServicesDesc: "Solutions numériques incluant plateformes en ligne, e-commerce et flux de travail automatisés.",
    dataAnalysis: "Analyse de Données",
    dataAnalysisDesc: "Transformation des données brutes en informations exploitables via visualisation, rapports et analyse statistique.",
    // FAQ
    faqTitle: "Questions Fréquentes",
    faqSubtitle: "Questions courantes sur mes services, disponibilité et processus de travail.",
    faqServicesQuestion: "Quels services proposez-vous?",
    faqServicesAnswer: "Je propose le développement web (React, Next.js, Node.js), le design graphique, les services électroniques (e-commerce, plateformes en ligne) et l'analyse de données. Mon objectif est de fournir des solutions d'ingénierie qui créent une valeur commerciale réelle.",
    faqFreelanceQuestion: "Êtes-vous disponible en freelance?",
    faqFreelanceAnswer: "Oui, je suis disponible pour des projets freelance, du travail contractuel et du conseil. Je travaille avec des startups, des agences et des entreprises de toutes tailles. N'hésitez pas à me contacter pour discuter de vos besoins.",
    faqTimelineQuestion: "Quel est votre délai de projet typique?",
    faqTimelineAnswer: "Les délais varient selon l'envergure du projet. Une page d'atterrissage simple prend 1-2 semaines, tandis que les applications full-stack prennent généralement 4-8 semaines. Je fournis des délais détaillés lors de notre consultation initiale et vous tiens informé tout au long du processus.",
    // Process
    processTitle: "Mon Processus",
    processSubtitle: "Une approche structurée pour livrer des solutions de haute qualité",
    processPlanning: "Planification",
    processPlanningDesc: "Compréhension des exigences, définition de la portée du projet et création d'une feuille de route alignée avec les objectifs commerciaux.",
    processDevelopment: "Développement",
    processDevelopmentDesc: "Construction de solutions évolutives avec du code propre, des technologies modernes et les meilleures pratiques.",
    processTesting: "Tests",
    processTestingDesc: "Assurance qualité rigoureuse, optimisation des performances et vérifications de compatibilité entre navigateurs.",
    processDeployment: "Déploiement",
    processDeploymentDesc: "Lancement fluide avec des pipelines CI/CD, configuration de surveillance et support post-lancement.",
    // Education
    educationTitle: "Éducation et Certifications",
    educationSubtitle: "Apprentissage continu et développement professionnel",
    educationA2: "Certificat A2 - Langue Allemande",
    educationA2Institution: "Goethe-Institut",
    educationA2Desc: "Certification officielle prouvant la maîtrise de la langue allemande au niveau élémentaire, permettant une communication professionnelle dans les environnements germanophones.",
    educationData: "Ingénierie des Données et DevOps",
    educationDataInstitution: "ALX Africa / Holberton School",
    educationDataDesc: "Formation complète en ingénierie des données, infrastructure cloud, pipelines CI/CD et meilleures pratiques DevOps avec expérience pratique sur des projets.",
    educationFullStack: "Ingénierie Logicielle Full Stack",
    educationFullStackInstitution: "ALX Africa / Holberton School",
    educationFullStackDesc: "Programme intensif couvrant le développement frontend et backend, l'ingénierie système et la programmation bas niveau avec C et Python.",
    certification: "Certification",
    degree: "Diplôme",
    viewCredential: "Voir le Certificat",
    // Hero
    heroProjects: "Projets",
    heroClients: "Clients",
    downloadCV: "Télécharger CV",
    byTheNumbers: "En Chiffres",
  },
  de: {
    // Navigation
    home: "Startseite",
    about: "Über mich",
    projects: "Projekte",
    blog: "Blog",
    contact: "Kontakt",
    settings: "Einstellungen",
    language: "Sprache",
    theme: "Design",
    // Home page
    webDeveloper: "Web- und Softwareentwickler",
    heroTitle: "Interaktive Apps mit ausgefeilter Ingenieurskunst.",
    heroDescription: "Ich entwickle Schnittstellen, die sich natürlich anfühlen, APIs, die zuverlässig skalieren, und Software, die echten Geschäftswert bietet. Erkunden Sie Arbeiten im Frontend-, Backend- und Full-Stack-Bereich.",
    seeProjects: "Projekte anzeigen",
    learnAbout: "Mehr über mich erfahren",
    projectsDelivered: "Projekte bereitgestellt",
    yearsExperience: "Jahre Erfahrung",
    techStack: "Technologie-Stack",
    designSystems: "Designsysteme für Skalierbarkeit",
    designSystemsDesc: "Wiederverwendbare UI-Muster, barrierefreie Layouts und komponentengesteuerte Workflows für schnelle Lieferung.",
    fullStack: "Full-Stack-Produktlieferung",
    fullStackDesc: "Von Frontend-Schnittstellen bis zu Backend-APIs liefere ich End-to-End-Lösungen mit Zuverlässigkeit und Geschwindigkeit.",
    highPerformance: "Hochleistungs-Erlebnisse",
    highPerformanceDesc: "Ich optimiere Ladevorgänge, Interaktionen und Visuals, damit sich Produkte poliert und reaktiv anfühlen.",
    // About page
    aboutMe: "Über mich",
    aboutTitle: "Löse Probleme mit Code und starkem Engineering.",
    aboutDesc: "Ich verbinde Frontend-Handwerk mit Backend-Zuverlässigkeit, um Produkte zu bauen, die Benutzer lieben und Teams warten können. Meine Arbeit basiert auf sauberer Architektur, schnellen Schnittstellen und einem klaren Entwicklungsprozess.",
    yearsCoding: "Jahre Code",
    deliveredProjects: "Ausgelieferte Projekte",
    careerHighlights: "Karriere-Meilensteine",
    fullStackLaunches: "Full-Stack-Launches",
    fullStackDetail: "Mehrere Produktionsanwendungen mit React-, Next.js- und Node.js-Integrationen bereitgestellt.",
    uxPerformance: "UX- und Leistungsfokus",
    uxDetail: "Baute polierte Benutzeroberflächen mit Barrierefreiheit, Geschwindigkeit und Animation im Hinterkopf.",
    softwareEngineering: "Grundlagen der Softwareentwicklung",
    softwareDetail: "Baute Backend-Services, REST-APIs und skalierbare Tools für moderne Web-Produkte.",
    howIWork: "So arbeite ich",
    plan: "Planen",
    planDesc: "Verstehen Sie das Problem, definieren Sie Ziele und stimmen Sie das Produkt mit den Bedürfnissen von Benutzern und Unternehmen ab.",
    build: "Bauen",
    buildDesc: "Schreiben Sie zuverlässigen Code mit modernen Tools, wiederverwendbaren Mustern und polierten UI-Interaktionen.",
    refine: "Verfeinern",
    refineDesc: "Testen, optimieren und warten Sie das Produkt, damit es schnell und leicht zu erweitern bleibt.",
    // Projects page
    projectsLabel: "Projekte",
    projectsTitle: "Echte Arbeit mit echtem Produktfokus.",
    projectsDesc: "Diese Projekte zeigen responsive Schnittstellen, solide Architektur und praktische Entwickler-Tools.",
    portfolioDashboard: "Portfolio-Dashboard",
    portfolioRole: "UI + Interaktionsdesign",
    portfolioSummary: "Ein sauberes, responsives Entwickler-Dashboard mit animierten UI-Komponenten und schnellem Ladeverhalten.",
    taskMgmt: "Aufgabenverwaltungs-App",
    taskRole: "Full-Stack-Lieferung",
    taskSummary: "Ein für Teams entwickeltes Produktivitätstool mit Aufgabenstatus, Persistenz und intuitivem Workflow.",
    apiSync: "API-Synchronisationsdienst",
    apiRole: "Backend-Architektur",
    apiSummary: "Ein Service, der mehrere APIs verbindet, Daten normalisiert und Systeme synchron hält.",
    designSystem: "Design System Kit",
    designRole: "Komponentenbibliothek",
    designSummary: "Ein wiederverwendbares Styling-System zur Beschleunigung der Design-Konsistenz über Apps hinweg.",
    // Blog page
    articles: "Artikel",
    blogTitle: "Gedanken zu Webentwicklung, Softwarearchitektur und modernen Tools.",
    blogDesc: "Teilen von Erkenntnissen aus Jahren des Aufbaus skalierbarer Webanwendungen und der Bewältigung realer technischer Herausforderungen.",
    readMore: "Lesen →",
    minRead: "Min Lesezeit",
    // Contact page
    contactLabel: "Kontakt",
    contactTitle: "Lassen Sie uns zusammen etwas Bedeutsames bauen.",
    contactDesc: "Ich bin offen für Webentwicklung, Softwaretechnik und Produktzusammenarbeit. Nehmen Sie Kontakt auf, um eine Idee, eine Auftragsarbeit oder ein technisches Projekt zu besprechen.",
    email: "E-Mail",
    visitProfile: "Profil besuchen",
    // Settings page
    settingsTitle: "Passen Sie Ihre Erfahrung an",
    settingsDescription: "Personalisieren Sie die Anzeigeeinstellungen Ihres Portfolios.",
    languageTitle: "Sprache",
    languageDescription: "Wähle deine bevorzugte Sprache für die Website.",
    accessibilityTitle: "Barrierefreiheit",
    fontSizeLabel: "Schriftgröße",
    notificationsTitle: "Benachrichtigungen",
    notificationsDescription: "Erhalte wichtige Updates und Nachrichten.",
    savedNote: "Deine Einstellungen werden lokal gespeichert.",
    // Services
    servicesTitle: "Ingenieurlösungen",
    servicesSubtitle: "Praktische Expertise in Design, Entwicklung und digitalen Dienstleistungen.",
    webDev: "Webentwicklung",
    webDevDesc: "Erstellung responsiver, leistungsstarker Websites mit modernen Technologien wie React, Next.js und Node.js.",
    graphicDesign: "Grafikdesign",
    graphicDesignDesc: "Entwicklung visueller Identitäten, UI/UX-Designs und Marketingmaterialien, die Ihre Marke effektiv kommunizieren.",
    eServices: "E-Dienstleistungen",
    eServicesDesc: "Digitale Lösungen wie Online-Plattformen, E-Commerce und automatisierte Workflows.",
    dataAnalysis: "Datenanalyse",
    dataAnalysisDesc: "Umwandlung von Rohdaten in umsetzbare Erkenntnisse durch Visualisierung, Berichterstattung und statistische Analyse.",
    // FAQ
    faqTitle: "Häufig Gestellte Fragen",
    faqSubtitle: "Häufige Fragen zu meinen Dienstleistungen, Verfügbarkeit und Arbeitsprozess.",
    faqServicesQuestion: "Welche Dienstleistungen bieten Sie an?",
    faqServicesAnswer: "Ich biete Webentwicklung (React, Next.js, Node.js), Grafikdesign, E-Dienstleistungen (E-Commerce, Online-Plattformen) und Datenanalyse an. Mein Fokus liegt auf Ingenieurlösungen, die echten Geschäftswert schaffen.",
    faqFreelanceQuestion: "Sind Sie für Freelance verfügbar?",
    faqFreelanceAnswer: "Ja, ich bin für Freelance-Projekte, Vertragsarbeit und Beratung verfügbar. Ich arbeite mit Startups, Agenturen und Unternehmen aller Größen. Kontaktieren Sie mich gerne, um Ihre Projektanforderungen zu besprechen.",
    faqTimelineQuestion: "Was ist Ihr typischer Projektzeitplan?",
    faqTimelineAnswer: "Zeitpläne variieren je nach Projektumfang. Eine einfache Landing Page dauert 1-2 Wochen, während Full-Stack-Anwendungen typischerweise 4-8 Wochen dauern. Ich gebe detaillierte Zeitpläne während unserer Erstberatung an und halte Sie während des gesamten Prozesses auf dem Laufenden.",
    // Process
    processTitle: "Mein Prozess",
    processSubtitle: "Ein strukturierter Ansatz zur Bereitstellung hochwertiger Lösungen",
    processPlanning: "Planung",
    processPlanningDesc: "Verständnis der Anforderungen, Definition des Projektumfangs und Erstellung einer Roadmap, die mit den Geschäftszielen übereinstimmt.",
    processDevelopment: "Entwicklung",
    processDevelopmentDesc: "Aufbau skalierbarer Lösungen mit sauberem Code, modernen Technologien und Best Practices.",
    processTesting: "Testen",
    processTestingDesc: "Rigouröse Qualitätssicherung, Leistungsoptimierung und Cross-Browser-Kompatibilitätsprüfungen.",
    processDeployment: "Bereitstellung",
    processDeploymentDesc: "Reibungsloser Launch mit CI/CD-Pipelines, Monitoring-Setup und Post-Launch-Support.",
    // Education
    educationTitle: "Bildung und Zertifizierungen",
    educationSubtitle: "Kontinuierliches Lernen und berufliche Entwicklung",
    educationA2: "A2 Zertifikat - Deutsche Sprache",
    educationA2Institution: "Goethe-Institut",
    educationA2Desc: "Offizielle Zertifizierung, die Kenntnisse der deutschen Sprache auf elementarem Niveau nachweist und professionelle Kommunikation in deutschsprachigen Umgebungen ermöglicht.",
    educationData: "Data & DevOps Engineering",
    educationDataInstitution: "ALX Africa / Holberton School",
    educationDataDesc: "Umfassende Schulung in Data Engineering, Cloud-Infrastruktur, CI/CD-Pipelines und DevOps-Best-Practices mit praktischer Projekterfahrung.",
    educationFullStack: "Full Stack Software Engineering",
    educationFullStackInstitution: "ALX Africa / Holberton School",
    educationFullStackDesc: "Intensives Programm mit Frontend- und Backend-Entwicklung, System Engineering und Low-Level-Programmierung mit C und Python.",
    certification: "Zertifizierung",
    degree: "Abschluss",
    viewCredential: "Zertifikat Ansehen",
    // Hero
    heroProjects: "Projekte",
    heroClients: "Kunden",
    downloadCV: "CV Herunterladen",
    byTheNumbers: "In Zahlen",
  },
  ja: {
    // Navigation
    home: "ホーム",
    about: "について",
    projects: "プロジェクト",
    blog: "ブログ",
    contact: "お問い合わせ",
    settings: "設定",
    language: "言語",
    theme: "テーマ",
    // Home page
    webDeveloper: "ウェブ・ソフトウェア開発者",
    heroTitle: "洗練されたエンジニアリングを備えたインタラクティブアプリ。",
    heroDescription: "自然に動くインターフェース、信頼性高くスケールするAPI、実ビジネス価値を支えるソフトウェアを構築します。フロントエンド、バックエンド、フルスタック開発にわたる作品をご覧ください。",
    seeProjects: "プロジェクトを見る",
    learnAbout: "詳しく知る",
    projectsDelivered: "納品プロジェクト",
    yearsExperience: "年の経験",
    techStack: "技術スタック",
    designSystems: "スケール向けに構築されたデザインシステム",
    designSystemsDesc: "再利用可能なUIパターン、アクセシビリティ優先のレイアウト、コンポーネント駆動ワークフローで迅速な納品を実現。",
    fullStack: "フルスタック製品デリバリー",
    fullStackDesc: "フロントエンドインターフェースからバックエンドAPIまで、信頼性とスピードを備えたエンドツーエンドソリューションを提供します。",
    highPerformance: "高パフォーマンスエクスペリエンス",
    highPerformanceDesc: "読み込み、インタラクション、ビジュアルを最適化し、製品が洗練されレスポンシブに感じられるようにします。",
    // About page
    aboutMe: "について",
    aboutTitle: "コードと強力なエンジニアリングで問題を解決します。",
    aboutDesc: "フロントエンドの職人技とバックエンドの信頼性を組み合わせて、ユーザーが楽しめ、チームが保守できる製品を構築します。私の作業は、クリーンアーキテクチャ、高速インターフェース、明確な開発プロセスに基づいています。",
    yearsCoding: "年のコーディング経験",
    deliveredProjects: "納品プロジェクト",
    careerHighlights: "キャリアハイライト",
    fullStackLaunches: "フルスタックローンチ",
    fullStackDetail: "React、Next.js、Node.jsの統合により、複数の本番環境アプリケーションを納品しました。",
    uxPerformance: "UXとパフォーマンスに焦点",
    uxDetail: "アクセシビリティ、スピード、アニメーションに配慮した、洗練されたユーザーインターフェースを構築しました。",
    softwareEngineering: "ソフトウェアエンジニアリングの基礎",
    softwareDetail: "バックエンドサービス、REST API、および最新のWebプロダクト向けのスケーラブルなツールを構築しました。",
    howIWork: "仕事のやり方",
    plan: "計画",
    planDesc: "問題を理解し、目標を定義し、製品をユーザーとビジネスのニーズと整合させます。",
    build: "構築",
    buildDesc: "最新のツール、再利用可能なパターン、洗練されたUI相互作用を使用して信頼性の高いコードを作成します。",
    refine: "改善",
    refineDesc: "テスト、最適化、製品の保守を行い、高速で拡張しやすい状態を保ちます。",
    // Projects page
    projectsLabel: "プロジェクト",
    projectsTitle: "本当に焦点を当てた実際の仕事。",
    projectsDesc: "これらのプロジェクトは、応答性の高いインターフェース、堅牢なアーキテクチャ、実用的な開発者ツールを強調しています。",
    portfolioDashboard: "ポートフォリオダッシュボード",
    portfolioRole: "UI+インタラクションデザイン",
    portfolioSummary: "アニメーションUIコンポーネントと高速読み込み動作を備えたクリーンでレスポンシブな開発者ダッシュボード。",
    taskMgmt: "タスク管理アプリ",
    taskRole: "フルスタックデリバリー",
    taskSummary: "チーム向けの生産性向上ツール。タスク状態、永続性、直感的なワークフローを備えています。",
    apiSync: "APISync Service",
    apiRole: "バックエンドアーキテクチャ",
    apiSummary: "複数のAPIを接続し、データを正規化し、システムを同期に保つサービス。",
    designSystem: "デザインシステムキット",
    designRole: "コンポーネントライブラリ",
    designSummary: "アプリ全体の設計の一貫性を加速させるために作成された再利用可能なスタイルシステム。",
    // Blog page
    articles: "記事",
    blogTitle: "Web開発、ソフトウェアアーキテクチャ、最新ツールに関する考え。",
    blogDesc: "スケーラブルなWebアプリケーションの構築と現実のエンジニアリング課題への対応から得た洞察を共有しています。",
    readMore: "読む →",
    minRead: "分読む",
    // Contact page
    contactLabel: "お問い合わせ",
    contactTitle: "一緒に意味のあるものを作りましょう。",
    contactDesc: "Web開発、ソフトウェアエンジニアリング、製品コラボレーションに対応しています。アイデア、請負の機会、またはテクニカルプロジェクトについて話し合うために、お便りください。",
    email: "メール",
    visitProfile: "プロフィールを訪問",
    // Settings page
    settingsTitle: "エクスペリエンスをカスタマイズ",
    settingsDescription: "ポートフォリオの表示設定をパーソナライズします。",
    languageTitle: "言語",
    languageDescription: "ウェブサイトの使用言語を選択してください。",
    accessibilityTitle: "アクセシビリティ",
    fontSizeLabel: "フォントサイズ",
    notificationsTitle: "通知",
    notificationsDescription: "重要な更新やメッセージを受け取ります。",
    savedNote: "設定はローカルに保存されます。",
    // Services
    servicesTitle: "エンジニアリングソリューション",
    servicesSubtitle: "デザイン、開発、デジタルサービスに関する実践的専門知識。",
    webDev: "ウェブ開発",
    webDevDesc: "React、Next.js、Node.jsなどの最新技術を使用した、レスポンシブで高性能なウェブサイトの構築。",
    graphicDesign: "グラフィックデザイン",
    graphicDesignDesc: "ブランドを効果的に伝えるビジュアルアイデンティティ、UI/UXデザイン、マーケティング資料の作成。",
    eServices: "電子サービス",
    eServicesDesc: "オンラインプラットフォーム、Eコマース、自動化ワークフローを含むデジタルソリューション。",
    dataAnalysis: "データ分析",
    dataAnalysisDesc: "可視化、レポート、統計分析を通じて生データを実用的な洞察に変換。",
    // FAQ
    faqTitle: "よくある質問",
    faqSubtitle: "サービス、対応状況、作業プロセスに関する一般的な質問。",
    faqServicesQuestion: "どのようなサービスを提供していますか？",
    faqServicesAnswer: "ウェブ開発（React、Next.js、Node.js）、グラフィックデザイン、電子サービス（Eコマース、オンラインプラットフォーム）、データ分析を提供しています。私の焦点は、実際のビジネス価値をもたらすエンジニアリングソリューションにあります。",
    faqFreelanceQuestion: "フリーランスは対応していますか？",
    faqFreelanceAnswer: "はい、フリーランスプロジェクト、契約業務、コンサルティングに対応しています。スタートアップ、代理店、あらゆる規模の企業とお仕事させていただいております。お気軽にご連絡ください。",
    faqTimelineQuestion: "典型的なプロジェクト期間はどのくらいですか？",
    faqTimelineAnswer: "期間はプロジェクトの範囲によって異なります。シンプルなランディングページは1-2週間、フルスタックアプリケーションは通常4-8週間かかります。初回相談時に詳細なスケジュールをご提示し、プロセス全体を通じて最新情報をお知らせします。",
    // Process
    processTitle: "マイプロセス",
    processSubtitle: "高品質なソリューションを提供するための構造化されたアプローチ",
    processPlanning: "計画",
    processPlanningDesc: "要件の理解、プロジェクト範囲の定義、ビジネス目標に合わせたロードマップの作成。",
    processDevelopment: "開発",
    processDevelopmentDesc: "クリーンコード、最新技術、ベストプラクティスを使用したスケーラブルなソリューションの構築。",
    processTesting: "テスト",
    processTestingDesc: "厳密な品質保証、パフォーマンス最適化、クロスブラウザ互換性チェック。",
    processDeployment: "デプロイメント",
    processDeploymentDesc: "CI/CDパイプラインによるスムーズなローンチ、モニタリング設定、ローンチ後のサポート。",
    // Education
    educationTitle: "教育と認定",
    educationSubtitle: "継続的な学習と専門的な発展",
    educationA2: "A2証明書 - ドイツ語",
    educationA2Institution: "Goethe-Institut",
    educationA2Desc: "初級レベルのドイツ語能力を証明する公式認定。ドイツ語環境での専門的なコミュニケーションを可能にします。",
    educationData: "データ・DevOpsエンジニアリング",
    educationDataInstitution: "ALX Africa / Holberton School",
    educationDataDesc: "データエンジニアリング、クラウドインフラ、CI/CDパイプライン、DevOpsベストプラクティスに関する包括的なトレーニングと実践的なプロジェクト経験。",
    educationFullStack: "フルスタックソフトウェアエンジニアリング",
    educationFullStackInstitution: "ALX Africa / Holberton School",
    educationFullStackDesc: "フロントエンドおよびバックエンド開発、システムエンジニアリング、CおよびPythonによる低レベルプログラミングをカバーする集中プログラム。",
    certification: "認定",
    degree: "学位",
    viewCredential: "認定を見る",
    // Hero
    heroProjects: "プロジェクト",
    heroClients: "クライアント",
    downloadCV: "CVをダウンロード",
    byTheNumbers: "数字で見る",
  },
  rw: {
    // Navigation
    home: "Ahabanza",
    about: "Ibyerekeye",
    projects: "Imishinga",
    blog: "Blog",
    contact: "Twandikire",
    settings: "Igenamiterere",
    language: "Ururimi",
    theme: "Icy tema",
    // Home page
    webDeveloper: "Ukora Website na Software",
    heroTitle: "App zikorera neza zubatswe n'ubuhanga bw'ubwenge.",
    heroDescription: "Nkora interfaces zikora neza, APIs zikomeza neza, na software ifasha abantu mu bikorwa by'ubucuruzi. Koresha imishinga yanjye yo mu frontend, backend, na full-stack.",
    seeProjects: "Reba Imishinga",
    learnAbout: "Menya Byinshi",
    projectsDelivered: "Imishinga yarangiye",
    yearsExperience: "Imyaka yo kubara",
    techStack: "Ibikoresho",
    designSystems: "Sistemu z'ubwoko zubatswe gukura",
    designSystemsDesc: "Ibice bya UI bongerera, layouts zihuriweho na accessibility, na workflows zikorerwa components byihuse.",
    fullStack: "Gukora products zuzuye",
    fullStackDesc: "Kuva ku frontend kugera ku backend, nkora solutions zuzuye zihuta kandi zikora neza.",
    highPerformance: "Uburambe bw'ibikorwa",
    highPerformanceDesc: "Nshimisha loading, interactions, na visuals kugira ngo products zikore neza.",
    // About page
    aboutMe: "Ibyerekeye Njyewe",
    aboutTitle: "Gukemura ibibazo ukoresheje ubuhanga bwa code.",
    aboutDesc: "Nhuza ubuhanga bwa frontend na backend kugira ngo nkore products abantu bakunda kandi abakozi bashobora kuyobora. Akazi kanjye kagizweho architecture nkeye, interfaces zihuta, na process y'iterambere irimwo.",
    yearsCoding: "Imyaka yo kwandika code",
    deliveredProjects: "Imishinga yarangiye",
    careerHighlights: "Ibihanga by'akazi",
    fullStackLaunches: "Gufungura full-stack",
    fullStackDetail: "Narangije apps zinini zikoresha React, Next.js, na Node.js.",
    uxPerformance: "Imbaraga kuri UX",
    uxDetail: "Nubatse interfaces z'abakoresha zirimo accessibility, speed, na animation.",
    softwareEngineering: "Inkingi zo gukora software",
    softwareDetail: "Nubatse backend services, REST APIs, na tools zikoresha products za web z'uyu munsi.",
    howIWork: "Uko nkora",
    plan: "Gutegura",
    planDesc: "Gusobanukirwa n'ikibazo, gushyiraho intego, no guhuza product n'ibyo abakoresha n'ubucuruzi bisabwa.",
    build: "Kubaka",
    buildDesc: "Kwandika code iza kukora neza ukoresheje ibikoresho bishya, patterns byongerera, na UI interactions.",
    refine: "Gusobanutsa",
    refineDesc: "Gukora tests, optimization, no kuyobora product kugira ngo ibe yihuta kandi yorohe gutera imbere.",
    // Projects page
    projectsLabel: "Imishinga",
    projectsTitle: "Akazi kuzuye kuzuyeho ibyo abantu basabwa.",
    projectsDesc: "Iyi mishinga iragaragaza interfaces zikorera, architecture ikomeye, na tools z'iterambere zikoreshwa.",
    portfolioDashboard: "Portfolio Dashboard",
    portfolioRole: "UI + design y'interaction",
    portfolioSummary: "Dashboard nziza y'umukozi w'iterambere ifite animated UI components na loading yihuta.",
    taskMgmt: "App yo Gucunga Imirimo",
    taskRole: "Full-stack delivery",
    taskSummary: "Igikoresho cy'imbaraga kibereye teams, ifite task states, persistence, na workflow yorohe.",
    apiSync: "Serivisi yo Guhuza API",
    apiRole: "Backend architecture",
    apiSummary: "Serivisi ihuza APIs nyinshi, itunganya data, ikandi ibika sistemu zihuzwa.",
    designSystem: "Kit y'Ibyiciro by'Imiterere",
    designRole: "Librarie ya components",
    designSummary: "Sistemu y'imiterere yongerera yubatswe kugira ngo yihute guhuza imiterere mu apps.",
    // Blog page
    articles: "Inyandiko",
    blogTitle: "Igitekerezo ku iterambere rya web, architecture ya software, na bikoresho bishya.",
    blogDesc: "Gusangira ibyabonetse mu myaka yubatse apps za web zikoresha kandi ngiye gukemura ibibazo by'ubwenge.",
    readMore: "Soma →",
    minRead: "umunota wo gusoma",
    // Contact page
    contactLabel: "Twandikire",
    contactTitle: "Tubake ibintu byagufasha hamwe.",
    contactDesc: "Ndi wafunguye ku iterambere rya web, software engineering, na collaborations z'ibicuruzwa. Andikira kuganira ku Ngingo cyangwa umwanya wo gukora.",
    email: "Email",
    visitProfile: "Sura Profile",
    // Settings page
    settingsTitle: "Hindura uko ubibona",
    settingsDescription: "Hindura ibyo ukunda byo kubona portfolio yawe.",
    languageTitle: "Ururimi",
    languageDescription: "Hitamo ururimi ukunda.",
    accessibilityTitle: "Fashabumenyi",
    fontSizeLabel: "Ingano y'inyuguti",
    notificationsTitle: "Amatangazo",
    notificationsDescription: "Wirinde amakuru ashyashya n'ubutumwa.",
    savedNote: "Ibyo wahisemo biguma mu mudasobwa yawe.",
    // Services
    servicesTitle: "Ibisubizo by'Ubuhanga",
    servicesSubtitle: "Ubumenyi buzuye mu miterere, iterambere, na serivisi za digital.",
    webDev: "Gukora Website",
    webDevDesc: "Kubaka websites zikorera kandi zikoresha neza ukoresheje React, Next.js, na Node.js.",
    graphicDesign: "Gukora Imiterere",
    graphicDesignDesc: "Gukora visual identities, designs za UI/UX, na materiya za marketing iziha imiterere brand yawe.",
    eServices: "Serivisi za Digital",
    eServicesDesc: "Ibisubizo bya digital birimo platforms za online, e-commerce, na workflows zikorwa na masinî.",
    dataAnalysis: "Gusuzuma Data",
    dataAnalysisDesc: "Guhindura data zikoreshwa mu nyandiko, raporo, na analysis ya statistique.",
    // FAQ
    faqTitle: "Ibibazo Bikunze Kubazwa",
    faqSubtitle: "Ibibazo rusange ku serivisi zanjye, kuboneka, na process y'akazi.",
    faqServicesQuestion: "Ni serivisi ki uha?",
    faqServicesAnswer: "Nha serivisi zo gukora website (React, Next.js, Node.js), gukora imiterere, e-services (e-commerce, platforms za online), na gusuzuma data. Intego yanjye ni ugufasha ubucuruzi kwiteza imbere.",
    faqFreelanceQuestion: "Wafunguye gukora freelance?",
    faqFreelanceAnswer: "Yego, ndi wafunguye ku mishinga ya freelance, akazi ka contract, na consulting. Nkora na startups, agences, na companies z'ingeri zose. Andikira kuganira.",
    faqTimelineQuestion: "Ighe giteganywa ry'umushinga ni gite?",
    faqTimelineAnswer: "Igihe kiva ku mushinga. Page yoroshe ya landing imara icyumweru 1-2, apps za full-stack zimara 4-8. Ndabagezaho igihe cyose.",
    // Process
    processTitle: "Uburyo Bwanjye",
    processSubtitle: "Uburyo bwubatswe kugira ngo hatanzwe ibisubizo bya high-quality",
    processPlanning: "Gutegura",
    processPlanningDesc: "Gusobanukirwa n'ibyo bisabwa, gushyiraho ingano y'umushinga, no gukora roadmap ihuriweho n'intego za business.",
    processDevelopment: "Iterambere",
    processDevelopmentDesc: "Kubaka solutions zikoresha neza ukoresheje code nziza, technologies z'uyu munsi, na best practices.",
    processTesting: "Gukora Test",
    processTestingDesc: "Quality assurance nziza, optimization y'imbaraga, na cross-browser compatibility checks.",
    processDeployment: "Gufungura",
    processDeploymentDesc: "Launch ryihuta ukoresheje CI/CD pipelines, monitoring setup, na support nyuma yo gufungura.",
    // Education
    educationTitle: "Amashuri na Certifications",
    educationSubtitle: "Gusoma iteka no kukura mu kazi",
    educationA2: "Certificate A2 - Ururimi rwa Gegemani",
    educationA2Institution: "Goethe-Institut",
    educationA2Desc: "Certification yemera ko wize ururimi rwa Gegemani ku rwego rwa shuri, ubashije kuganira mu mishinga y'ururimi rwa Gegemani.",
    educationData: "Data & DevOps Engineering",
    educationDataInstitution: "ALX Africa / Holberton School",
    educationDataDesc: "Amahugurwa yuzuye kuri data engineering, cloud infrastructure, CI/CD pipelines, na DevOps best practices ukoresheje imishinga yo mu by'ukuri.",
    educationFullStack: "Full Stack Software Engineering",
    educationFullStackInstitution: "ALX Africa / Holberton School",
    educationFullStackDesc: "Porogarame yihuta ikora frontend na backend development, system engineering, na low-level programming ukoresheje C na Python.",
    certification: "Certification",
    degree: "Degree",
    viewCredential: "Reba Certificate",
    // Hero
    heroProjects: "Imishinga",
    heroClients: "Abakiriya",
    downloadCV: "Download CV",
    byTheNumbers: "Mu Njugu",
  },
};

type Language = keyof typeof translations;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (typeof translations)[Language];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  // Load language from localStorage on mount
  useEffect(() => {
    setMounted(true);
    const storedLanguage = localStorage.getItem("language") as Language | null;
    if (storedLanguage && translations[storedLanguage]) {
      setLanguageState(storedLanguage);
      if (typeof document !== "undefined") {
        document.documentElement.lang = storedLanguage;
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    // Update HTML lang attribute
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
